security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt: ~
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }

        - { path: ^/api/books/\d+$, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/books/?$, methods: [ GET ], roles: PUBLIC_ACCESS }

        - { path: ^/api/books/\d+$, methods: [ PUT, DELETE ], roles: ROLE_ADMIN }
        - { path: ^/api/books/?$, methods: [ POST ], roles: ROLE_ADMIN }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: PUBLIC_ACCESS }

